# Generated by Django 3.1 on 2020-08-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=256)),
                ('kana', models.CharField(max_length=256)),
                ('pos', models.CharField(max_length=256)),
                ('meaning', models.CharField(max_length=256)),
                ('en_example', models.CharField(max_length=256)),
                ('ja_example', models.CharField(max_length=256)),
                ('level', models.CharField(max_length=32)),
            ],
        ),
    ]
